server.port=8081
spring.application.name=expense-tracking

spring.data.mongodb.host=${MONGO_HOST:localhost}
spring.data.mongodb.port=27017
spring.data.mongodb.database=expense_tracking

ai.api.key=${AI_API_KEY}
